repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.3
  hooks:
  - id: poetry-check
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
      exclude: '\.py$'  # This regex excludes all Python files
    - id: check-json
    - id: check-xml
    - id: check-yaml
      name: Check MkDocs.yml in unsafe mode
      files: ^mkdocs\.yml$
      args: ['--unsafe']
    - id: check-yaml
      name: Check all other YAML files in safe mode
      files: \.ya?ml$
      exclude: ^mkdocs\.yml$
    - id: debug-statements
    - id: end-of-file-fixer
      exclude: ^docs/
    - id: pretty-format-json
      exclude: ^notebooks/
      args: ['--autofix']
    - id: trailing-whitespace
      exclude: ^docs/
        # Make sure windows user don't push CRLF terminated files
        # More doc about it: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
    - id: mixed-line-ending
      args: ['--fix=lf']
      exclude: ^docs/
    - id: detect-private-key
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.10.1'
  hooks:
    - id: mypy
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      # Exclude tests bc they contain assert statements, that raise bandit errors
      exclude: tests/
