solution:  "/Users/lstefanu/Documents/perso/kaggle/rnafold/data/validation_labels.csv"
submission: "/Users/lstefanu/Documents/perso/kaggle/rnafold/data/sample_submission.csv"
usalign_bin: "/opt/homebrew/bin/usalign"
